var dir_f2306d1b140220194aa842ed96c8d36f =
[
    [ "complete.cpp", "complete_8cpp.html", "complete_8cpp" ],
    [ "complete.h", "complete_8h.html", "complete_8h" ],
    [ "constant_inequality.cpp", "constant__inequality_8cpp.html", "constant__inequality_8cpp" ],
    [ "constant_inequality.h", "constant__inequality_8h.html", "constant__inequality_8h" ],
    [ "coordinate.cpp", "coordinate_8cpp.html", "coordinate_8cpp" ],
    [ "coordinate.h", "coordinate_8h.html", "coordinate_8h" ],
    [ "dyadic_inequality.cpp", "dyadic__inequality_8cpp.html", "dyadic__inequality_8cpp" ],
    [ "dyadic_inequality.h", "dyadic__inequality_8h.html", "dyadic__inequality_8h" ],
    [ "inequality.cpp", "inequality_8cpp.html", "inequality_8cpp" ],
    [ "inequality.h", "inequality_8h.html", "inequality_8h" ],
    [ "inequality_factory.cpp", "inequality__factory_8cpp.html", null ],
    [ "inequality_factory.h", "inequality__factory_8h.html", "inequality__factory_8h" ],
    [ "join.cpp", "join_8cpp.html", "join_8cpp" ],
    [ "join.h", "join_8h.html", "join_8h" ],
    [ "parser.cpp", "solvers_2tvpi_2parser_8cpp.html", null ],
    [ "parser.h", "solvers_2tvpi_2parser_8h.html", "solvers_2tvpi_2parser_8h" ],
    [ "planar_comparator.cpp", "planar__comparator_8cpp.html", null ],
    [ "planar_comparator.h", "planar__comparator_8h.html", "planar__comparator_8h" ],
    [ "smt_printer.cpp", "smt__printer_8cpp.html", null ],
    [ "smt_printer.h", "smt__printer_8h.html", "smt__printer_8h" ],
    [ "tikz_printer.cpp", "tikz__printer_8cpp.html", null ],
    [ "tikz_printer.h", "tikz__printer_8h.html", "tikz__printer_8h" ],
    [ "tvpi_math.cpp", "tvpi__math_8cpp.html", "tvpi__math_8cpp" ],
    [ "tvpi_systemt.cpp", "tvpi__systemt_8cpp.html", null ],
    [ "tvpi_systemt.h", "tvpi__systemt_8h.html", "tvpi__systemt_8h" ],
    [ "unary_inequality.cpp", "unary__inequality_8cpp.html", "unary__inequality_8cpp" ],
    [ "unary_inequality.h", "unary__inequality_8h.html", "unary__inequality_8h" ],
    [ "vertex.cpp", "vertex_8cpp.html", null ],
    [ "vertex.h", "vertex_8h.html", "vertex_8h" ]
];